DROP DATABASE IF EXISTS bd;
CREATE DATABASE bd;

USE bd;


CREATE TABLE PERSONAJES (ID INT NOT NULL, FUERZA INT, HP INT, VELOCIDAD INT, MAGIA INT, PRIMARY KEY(ID)) ENGINE = InnoDB;

CREATE TABLE PARTIDAS (ID INT NOT NULL, NUM_JUG INT, DURACION FLOAT, PRIMARY KEY(ID)) ENGINE= InnoDB;

CREATE TABLE USUARIOS (ID INT NOT NULL, NOMBRE VARCHAR(30), CORREO VARCHAR(60),CONTRASEÑA VARCHAR(30), ID_PERS INT NOT NULL, SCORE INT, ID_PARTIDA INT NOT NULL, PRIMARY KEY(ID), FOREIGN KEY (ID_PERS) REFERENCES PERSONAJES(ID), FOREIGN KEY (ID_PARTIDA) REFERENCES PARTIDAS(ID)) ENGINE = InnoDB;


INSERT INTO PARTIDAS VALUES (1, 4, 5);
INSERT INTO PERSONAJES VALUES (1, 5, 10, 3, 2);
INSERT INTO PERSONAJES VALUES (2, 15, 20, 2, 2);
INSERT INTO PERSONAJES VALUES (3, 8, 12, 6, 6);
INSERT INTO PERSONAJES VALUES (4, 9, 9, 10, 9);
INSERT INTO PERSONAJES VALUES (5, 3, 10, 3, 15);

INSERT INTO USUARIOS VALUES (1, 'MANOLO','manoloeselmejor@gmail.es', '1234', 1, 10, 1);
INSERT INTO USUARIOS VALUES (2, 'PACO','paquitoelchocolatero@hotmail.com', '1975', 3, 15, 1);
INSERT INTO USUARIOS VALUES (3, 'FERNANDO','merepetiesesenumerin@icloud.com', '33', 5, 8, 1);
INSERT INTO USUARIOS VALUES (4, 'SARA','aragon@gmail.es', 'est@EsM3J0r#', 2, 20, 1);


SHOW TABLES;